### ISSUE TITLE
cluodwatch グループのエラー

### ISSUE THREAD

**Issue by comu2e** [Snails8/terraform-ecs-prd-dev#7]
https://github.com/Snails8/terraform-ecs-prd-dev/blob/831d86a7cd1189b24058bf0ce5cc36aa4dc69c8b/src/_module/ecs/frontend/main.tf#L69

ecsのタスク定義と整合性取るために下記に変更必要。

resource "aws_cloudwatch_log_group" "frontend" {
  name              = "/${var.app_name}/frontend"
  retention_in_days = 7
}

**Comment by Snails8** [comment]
ありがとうございます。確認します。
